import { Eye } from 'lucide-react'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Card, CardContent } from '@/components/ui/card'
import {
  Table,
  TableBody,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { prisma } from '@/lib/db'
import {
  currentMonthInput,
  formatCurrency,
  formatMonth,
  monthInputToDate,
  toNumber,
} from '@/lib/format'
import { AddPayoutDialog } from '../../_components/add-payout-dialog'
import { MonthPicker } from '../../_components/month-picker'
import { PaymentStatusBadge } from '../../_components/status-badge'

export const metadata: Metadata = { title: 'Payout Management' }

export default async function PayoutsPage({
  searchParams,
}: {
  searchParams: Promise<{ month?: string }>
}) {
  const params = await searchParams
  const monthInput = params.month && monthInputToDate(params.month) ? params.month : currentMonthInput()
  const month = monthInputToDate(monthInput)!

  const [entries, approvedDsas, loanTypesSetting] = await Promise.all([
    prisma.payout.findMany({
      where: { month },
      select: {
        userId: true,
        amount: true,
        paidAmount: true,
        user: { select: { fullName: true, email: true } },
      },
    }),
    prisma.user.findMany({
      where: { role: 'DSA', status: 'APPROVED' },
      orderBy: { fullName: 'asc' },
      select: { id: true, fullName: true, email: true, mobile: true },
    }),
    prisma.setting.findUnique({ where: { key: 'loan_types' } }),
  ])

  // Roll the per-category rows up to one line per DSA, which is what §7.3 shows.
  const byDsa = new Map<
    string,
    { name: string; email: string; total: number; paid: number }
  >()
  for (const entry of entries) {
    const existing = byDsa.get(entry.userId) ?? {
      name: entry.user.fullName,
      email: entry.user.email,
      total: 0,
      paid: 0,
    }
    existing.total += toNumber(entry.amount)
    existing.paid += toNumber(entry.paidAmount)
    byDsa.set(entry.userId, existing)
  }

  const rows = [...byDsa.entries()].sort((a, b) => a[1].name.localeCompare(b[1].name))
  const totals = rows.reduce(
    (acc, [, row]) => ({ total: acc.total + row.total, paid: acc.paid + row.paid }),
    { total: 0, paid: 0 },
  )

  const loanTypes = Array.isArray(loanTypesSetting?.value)
    ? (loanTypesSetting.value as string[])
    : []

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <h1 className="font-serif text-3xl font-medium text-navy-deep">Payout Management</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Every figure and slip on this screen is entered manually. Nothing is calculated or
            generated by the panel.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <MonthPicker value={monthInput} />
          <AddPayoutDialog dsas={approvedDsas} loanTypes={loanTypes} defaultMonth={monthInput} />
        </div>
      </div>

      <Card>
        <CardContent className="border-b pb-(--card-spacing)">
          <h2 className="text-base font-medium text-navy-deep">
            Payout overview — {formatMonth(month)}
          </h2>
          <p className="text-sm text-muted-foreground">
            One row per DSA, summed across all five payout categories.
          </p>
        </CardContent>

        <CardContent className="px-0">
          {rows.length === 0 ? (
            <p className="px-(--card-spacing) py-12 text-center text-sm text-muted-foreground">
              No payouts recorded for {formatMonth(month)}.
              {approvedDsas.length === 0
                ? ' Approve a DSA registration first.'
                : ' Use “Add Payout” to record one.'}
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-12 pl-(--card-spacing)">#</TableHead>
                  <TableHead>DSA Name</TableHead>
                  <TableHead>Email</TableHead>
                  <TableHead className="text-right">Total Earnings</TableHead>
                  <TableHead className="text-right">DSA Payout</TableHead>
                  <TableHead className="text-right">Payable Amount</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="pr-(--card-spacing) text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {rows.map(([userId, row], i) => (
                  <TableRow key={userId}>
                    <TableCell className="pl-(--card-spacing) text-muted-foreground">
                      {i + 1}
                    </TableCell>
                    <TableCell className="font-medium text-navy-deep">{row.name}</TableCell>
                    <TableCell className="text-muted-foreground">{row.email}</TableCell>
                    <TableCell className="text-right tabular-nums">
                      {formatCurrency(row.total)}
                    </TableCell>
                    <TableCell className="text-right tabular-nums">
                      {formatCurrency(row.paid)}
                    </TableCell>
                    <TableCell className="text-right tabular-nums">
                      {formatCurrency(row.total - row.paid)}
                    </TableCell>
                    <TableCell>
                      <PaymentStatusBadge total={row.total} paid={row.paid} />
                    </TableCell>
                    <TableCell className="pr-(--card-spacing) text-right">
                      <Link
                        href={`/admin/payouts/${userId}?month=${monthInput}`}
                        className="inline-flex items-center gap-1.5 text-sm font-medium text-gold-dark hover:underline"
                      >
                        <Eye className="size-3.5" aria-hidden />
                        View Details
                      </Link>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
              <TableFooter>
                <TableRow>
                  <TableCell colSpan={3} className="pl-(--card-spacing) font-medium">
                    Total
                  </TableCell>
                  <TableCell className="text-right font-medium tabular-nums">
                    {formatCurrency(totals.total)}
                  </TableCell>
                  <TableCell className="text-right font-medium tabular-nums">
                    {formatCurrency(totals.paid)}
                  </TableCell>
                  <TableCell className="text-right font-medium tabular-nums">
                    {formatCurrency(totals.total - totals.paid)}
                  </TableCell>
                  <TableCell colSpan={2} />
                </TableRow>
              </TableFooter>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
