/**
 * Walks a payout from admin entry to the DSA seeing and being notified of it,
 * using the same services the admin panel calls.
 *
 *   pnpm walkthrough:payout
 *
 * Expects the DSA created by `pnpm walkthrough`. Re-running clears that DSA's
 * payouts and payout notifications first, so it is safe to repeat.
 */
import 'dotenv/config'

// Pin the disk driver so the test never depends on a CDN being reachable.
process.env.STORAGE_DRIVER = 'disk'

import { prisma } from '../lib/db'
import { formatCurrency, formatMonth, monthInputToDate, toNumber } from '../lib/format'
import {
  createPayout,
  publishPayoutEntry,
  recordPayment,
  replaceSlip,
} from '../lib/services/payouts'

const EMAIL = 'akshitcontact007@gmail.com'
const MONTH = monthInputToDate('2026-09')!

function step(n: number, title: string) {
  console.log(`\n${'─'.repeat(72)}\nSTEP ${n} — ${title}\n${'─'.repeat(72)}`)
}

function ok(label: string, detail = '') {
  console.log(`  [ok]    ${label}${detail ? ` — ${detail}` : ''}`)
}

function blocked(label: string, detail = '') {
  console.log(`  [block] ${label}${detail ? ` — ${detail}` : ''}`)
}

function info(label: string, value: unknown) {
  console.log(`          ${label.padEnd(26)} ${String(value)}`)
}

function slipFile() {
  return new File([Buffer.from('%PDF-1.4 dummy salary slip')], 'slip-sep-2026.pdf', {
    type: 'application/pdf',
  })
}

/** What the DSA dashboard would show: PENDING entries are excluded. */
async function dsaVisiblePayouts(userId: string) {
  return prisma.payout.findMany({
    where: { userId, status: { in: ['PUBLISHED', 'PAID'] } },
    orderBy: { createdAt: 'asc' },
  })
}

async function dsaNotifications(userId: string) {
  return prisma.notification.findMany({
    where: { userId, type: { in: ['payout_published', 'payout_paid'] } },
    orderBy: { createdAt: 'asc' },
  })
}

async function main() {
  const admin = await prisma.user.findFirstOrThrow({ where: { role: 'ADMIN' } })
  const akshit = await prisma.user.findUnique({ where: { email: EMAIL } })

  if (!akshit || akshit.status !== 'APPROVED') {
    console.log(`\n  No approved DSA for ${EMAIL}. Run: pnpm walkthrough\n`)
    process.exitCode = 1
    return
  }

  // Clean slate for a repeatable run.
  await prisma.payout.deleteMany({ where: { userId: akshit.id } })
  await prisma.notification.deleteMany({
    where: { userId: akshit.id, type: { in: ['payout_published', 'payout_paid'] } },
  })

  console.log(`\n  Paying ${akshit.fullName} (${akshit.referCode}) for ${formatMonth(MONTH)}`)

  // ── 1. Admin records the payout, unpublished ─────────────────────────────
  step(1, 'Admin records a payout — status Pending')
  const created = await createPayout({
    adminId: admin.id,
    userId: akshit.id,
    month: MONTH,
    category: 'LOAN',
    loanType: 'Home Loan',
    amount: 45000,
    remarks: 'Home loan disbursed — HDFC, file HL-20260901',
    status: 'PENDING',
  })
  if (!created.ok) {
    console.log(`  [FAIL] ${created.error}`)
    process.exitCode = 1
    return
  }
  const payoutId = created.payoutId!
  ok('Payout created', `${formatCurrency(45000)} · Loan Categories / Home Loan`)

  info('Visible to Akshit now', (await dsaVisiblePayouts(akshit.id)).length)
  info('Notifications sent', (await dsaNotifications(akshit.id)).length)
  ok('Pending payouts are hidden from the DSA', 'spec §9.1')

  // ── 2. Publishing without a slip is refused ──────────────────────────────
  step(2, 'Admin tries to publish before uploading the slip')
  const premature = await publishPayoutEntry({ adminId: admin.id, payoutId })
  if (premature.ok) {
    console.log('  [FAIL] publishing without a slip should have been refused')
    process.exitCode = 1
    return
  }
  blocked('Refused', premature.error)

  // ── 3. Admin uploads the slip ────────────────────────────────────────────
  step(3, 'Admin uploads the salary slip they prepared')
  const uploaded = await replaceSlip({ adminId: admin.id, payoutId, file: slipFile() })
  if (!uploaded.ok) {
    console.log(`  [FAIL] ${uploaded.error}`)
    process.exitCode = 1
    return
  }
  const withSlip = await prisma.payout.findUniqueOrThrow({ where: { id: payoutId } })
  ok('Slip stored', withSlip.slipFileUrl ?? '')
  ok('Not generated by the panel', 'this is the exact file the admin uploaded')

  // ── 4. Publish ───────────────────────────────────────────────────────────
  step(4, 'Admin publishes the payout')
  const published = await publishPayoutEntry({ adminId: admin.id, payoutId })
  if (!published.ok) {
    console.log(`  [FAIL] ${published.error}`)
    process.exitCode = 1
    return
  }
  ok('Published', published.message)

  const afterPublish = await dsaVisiblePayouts(akshit.id)
  info('Visible to Akshit now', afterPublish.length)
  info('Status', afterPublish[0]?.status)
  info('Amount', formatCurrency(afterPublish[0]?.amount ?? 0))
  info('Paid so far', formatCurrency(afterPublish[0]?.paidAmount ?? 0))

  for (const n of await dsaNotifications(akshit.id)) {
    ok(`Akshit notified: "${n.title}"`, n.channels.join(', '))
    info('  message', n.message)
  }

  // ── 5. Partial payment ───────────────────────────────────────────────────
  step(5, 'Admin records a partial payment of ₹20,000')
  const partial = await recordPayment({ adminId: admin.id, payoutId, paidAmount: 20000 })
  if (!partial.ok) {
    console.log(`  [FAIL] ${partial.error}`)
    process.exitCode = 1
    return
  }
  ok('Recorded', partial.message)

  const afterPartial = await prisma.payout.findUniqueOrThrow({ where: { id: payoutId } })
  const paid = toNumber(afterPartial.paidAmount)
  const total = toNumber(afterPartial.amount)
  info('Status', afterPartial.status)
  info('Payment indicator', paid >= total ? 'Paid' : paid > 0 ? 'Partial' : 'Unpaid')
  info('Payable remaining', formatCurrency(total - paid))
  info('Paid notifications so far', (await dsaNotifications(akshit.id)).filter((n) => n.type === 'payout_paid').length)
  ok('No "payment received" notice yet', 'it is not paid in full')

  // ── 6. Settle in full ────────────────────────────────────────────────────
  step(6, 'Admin settles the remaining ₹25,000')
  const settled = await recordPayment({ adminId: admin.id, payoutId, paidAmount: 45000 })
  if (!settled.ok) {
    console.log(`  [FAIL] ${settled.error}`)
    process.exitCode = 1
    return
  }
  ok('Recorded', settled.message)

  const final = await prisma.payout.findUniqueOrThrow({ where: { id: payoutId } })
  info('Status', final.status)
  info('Paid at', final.paidAt?.toISOString())
  info('Payment indicator', 'Paid')

  // ── 7. What Akshit sees ──────────────────────────────────────────────────
  step(7, 'Akshit opens the DSA panel')
  const visible = await dsaVisiblePayouts(akshit.id)
  for (const p of visible) {
    console.log(`  Payouts page — ${formatMonth(p.month)}`)
    info('Category', `${p.category}${p.loanType ? ` / ${p.loanType}` : ''}`)
    info('Amount', formatCurrency(p.amount))
    info('Paid', formatCurrency(p.paidAmount))
    info('Status', p.status)
    info('Salary slip', p.slipFileUrl ? `downloadable — ${p.slipFileUrl}` : 'Slip not uploaded yet')
  }

  console.log('\n  Notification centre:')
  for (const n of await dsaNotifications(akshit.id)) {
    console.log(`    • ${n.title} — ${n.message}`)
    console.log(`      channels: ${n.channels.join(', ')} · unread: ${n.readAt === null}`)
  }

  // ── 8. Duplicate settlement must not re-notify ───────────────────────────
  step(8, 'Admin re-saves the same paid amount')
  await recordPayment({ adminId: admin.id, payoutId, paidAmount: 45000 })
  const paidNotices = (await dsaNotifications(akshit.id)).filter((n) => n.type === 'payout_paid')
  if (paidNotices.length !== 1) {
    console.log(`  [FAIL] expected exactly one paid notice, found ${paidNotices.length}`)
    process.exitCode = 1
    return
  }
  ok('Still exactly one "Payment Received" notice', 'no duplicate on re-save')

  const unread = await prisma.notification.count({
    where: { userId: akshit.id, readAt: null },
  })
  console.log(`\n${'─'.repeat(72)}\nCHECK IT IN THE BROWSER\n${'─'.repeat(72)}`)
  console.log(`  Log in as     ${EMAIL} / Akshit@2026`)
  console.log(`  Payouts       http://localhost:3000/dsa/payouts`)
  console.log(`  Notifications http://localhost:3000/dsa/notifications  (${unread} unread)`)
  console.log(`  Admin view    http://localhost:3000/admin/payouts/${akshit.id}?month=2026-09\n`)
}

main()
  .catch((error) => {
    console.error(error)
    process.exitCode = 1
  })
  .finally(() => prisma.$disconnect())
